export const FETCH_POSTS = "FETCH_POSTS";
export const NEW_POST = "NEW_POST";
export const VOLUNTEER_DIALOG_OPEN = "VOLUNTEER_DIALOG_OPEN";
export const VOLUNTEER_DIALOG_CLOSE = "VOLUNTEER_DIALOG_CLOSE";
export const NEW_VOLUNTEER = "NEW_VOLUNTEER";
export const UPDATE_VOLUNTEERS = "UPDATE_VOLUNTEERS";
export const UPDATE_VOLUNTEER = "UPDATE_VOLUNTEER";
